# -*- coding: utf-8 -*-
"""iris.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WTh1nwObfeHRQErwSxXPn1btAJNjXLSf
"""

import matplotlib.pyplot as plt
from sklearn.datasets import load_iris
f=load_iris()
dir(f)

print(f.data[0])

from numpy.random import rand
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(f.data,f.target,random_state=42)

from sklearn.linear_model import LogisticRegression
model=LogisticRegression()

model.fit(x_train,y_train)

model.score(x_test,y_test)

model.predict(x_test)