# -*- coding: utf-8 -*-
"""kmean.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bfKDToEYiJqHh373IjFnBqd1A6VvFs3d
"""

import pandas as pd
from sklearn.datasets import load_iris
li=load_iris()
dir(li)

li.target_names

li.feature_names

df=pd.DataFrame(li.data,columns=li.feature_names)

df

df=df[['sepal length (cm)','petal length (cm)']]
df

df['target']=li.target

import matplotlib.pyplot as plt
plt.scatter(df['petal length (cm)'],df['sepal length (cm)'],c=df['target'])
plt.xlabel('sepal')
plt.ylabel('petal')
plt.colorbar(label='Target Class')
plt.show()

from sklearn.cluster import KMeans
model=KMeans(n_clusters=3)

from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(df,li.target,test_size=0.2,random_state=42)
model.fit(x_train,y_train)

y_pred=model.predict(x_test)

model.score()

