# -*- coding: utf-8 -*-
"""knn.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uvR01EfK5K16fsDmNub9mqGnzimOcOLu
"""

from sklearn.datasets import load_digits
ld=load_digits()
dir(ld)

ld.data

import pandas as pd
df=pd.DataFrame(ld.data,columns=ld.feature_names)
df

from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(ld.data,ld.target,test_size=0.2)

from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
x_train=sc.fit_transform(x_train)
x_test=sc.transform(x_test)

from sklearn.neighbors import KNeighborsClassifier
model=KNeighborsClassifier(n_neighbors=10)
model.fit(x_train,y_train)

y_predict=model.predict(x_test)

model.score(x_test,y_test)

from sklearn.metrics import confusion_matrix
cm=confusion_matrix(y_test,y_predict)

cm

import matplotlib.pyplot as plt
import seaborn as sn
plt.figure(figsize=(7,5))
sn.heatmap(cm, annot=True)
plt.xlabel('Predicted')
plt.ylabel('Truth')

