# -*- coding: utf-8 -*-
"""Logisticregression

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1daVu7SDXqD6Wb65Pxe0GQ9z8U2JZIpFS
"""

#mounting to drive
from google.colab import drive
drive.mount('/content/drive')

!ls '/content/drive/MyDrive'

import pandas as pd
df = pd.read_csv('/content/drive/MyDrive/HR_comma_sep.csv')
df

df.isnull().sum()

df.dtypes

(df == ' ').sum()

cat_col = df.select_dtypes(include='object')

X = df.drop('left', axis=1)
y = df['left']

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

ct = ColumnTransformer(
    transformers=[('encoder', OneHotEncoder(), ['Department', 'salary'])],
    remainder='passthrough'
)

X_train_transformed = ct.fit_transform(X_train)
X_test_transformed = ct.transform(X_test)

from sklearn.linear_model import LogisticRegression
lr = LogisticRegression(max_iter=1000)
lr.fit(X_train_transformed, y_train)

y_pred = lr.predict(X_test_transformed)

lr.predict(X_test_transformed)

from sklearn.metrics import accuracy_score

accuracy_score(y_test, lr.predict(X_test_transformed))

from sklearn.metrics import classification_report, confusion_matrix

y_pred = lr.predict(X_test_transformed)

print('Classification Report:')
print(classification_report(y_test, y_pred))

print('\nConfusion Matrix:')
print(confusion_matrix(y_test, y_pred))

import joblib
joblib.dump(lr, 'logistic_regression_model.joblib')
joblib.dump(ct, 'column_transformer.joblib')

new_data = {
    'satisfaction_level': 0.62,
    'last_evaluation': 0.75,
    'number_project': 4,
    'average_montly_hours': 210,
    'time_spend_company': 5,
    'Work_accident': 0,
    'promotion_last_5years': 0,
    'Department': 'IT',
    'salary': 'high'
}

new_df = pd.DataFrame(new_data, index=[0])
new_df

new_transform = ct.transform(new_df)
new_transform

pre = lr.predict(new_transform)
pre