# -*- coding: utf-8 -*-
"""random.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xxDSQI8hozODmGNBnmK2CNLCF94P3S7X
"""

import pandas as pd
from sklearn.datasets import load_digits
dig=load_digits()

x=dig.data
y=dig.target
y

from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=0)

from sklearn.ensemble import RandomForestClassifier
model=RandomForestClassifier(n_estimators=40)
model.fit(x_train,y_train)

model.predict(x_test)

model.score(x_test,y_test)

model.score(x_train,y_train)

