# -*- coding: utf-8 -*-
"""pathole_crack_detect

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12XFvRHBUfUivArdHxPfZAiYEi94Sp9hq
"""

!uv pip install ultralytics
import ultralytics
ultralytics.checks()

from google.colab import drive
drive.mount('/content/gdrive')

!ls /content/gdrive/MyDrive/dataset

# Commented out IPython magic to ensure Python compatibility.
# %%writefile /content/dataset.yaml
# path: /content/gdrive/MyDrive/dataset
# train: train
# val: val
# test: test
# 
# names:
#   0: cracks
#   1: patholes

!ls /content/gdrive/MyDrive/dataset

!yolo segment train data=/content/dataset.yaml model=yolov8n-seg.pt epochs=30 imgsz=640 batch=16

!ls /content/runs/segment

!ls /content/runs/segment/train-3/weights

!cp /content/runs/segment/train-3/weights/best.pt /content/gdrive/MyDrive/models/

!yolo segment predict model=/content/gdrive/MyDrive/models/best.pt source='/content/gdrive/MyDrive/dataset/test/vlcsnap-2025-02-19-14h44m07s468.jpg' conf=0.1

!yolo segment predict model=/content/gdrive/MyDrive/models/best.pt source='/content/gdrive/MyDrive/dataset/test' conf=0.1

