# -*- coding: utf-8 -*-
"""naive.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PZQqEZ7CY6Vp7QnNLdny0dlriAcLupKm
"""

from sklearn.datasets import load_wine
import pandas as pd
lw=load_wine()
dir(lw)

lw.feature_names

lw.target_names

df=pd.DataFrame(lw.data,columns=lw.feature_names)
df.head()

df.dtypes

from sklearn.naive_bayes import GaussianNB
model=GaussianNB()

x=df
y=lw.target

from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)

from sklearn.preprocessing import MinMaxScaler
scaler=MinMaxScaler()
x_train=scaler.fit_transform(x_train)
x_test=scaler.transform(x_test)

model.fit(x_train,y_train)

model.predict(x_test)

model.score(x_test,y_test)

from sklearn.naive_bayes import MultinomialNB
model1=MultinomialNB()

model1.fit(x_train,y_train)

model1.predict(x_test)

model1.score(x_test,y_test)

